### ISSUE TITLE
properties为什么要用对象而不用数组，能保证顺序吗

### ISSUE THREAD

**Issue by vivialex** [chengaohe45/vue-easy-form#1]

**Comment by chengaohe45** [comment]
这确实是一个好问题。

为什么使用对象？
vue-easy-form设计的目的就是跟后端接口字段1比1匹配，现在后端接口基本都是采用键值对的方式来提交，采用对象的方式正好可以跟这种调用方式天然匹配，且可无限层级下去，相对数组写法，可读性更强，如有页面1，页面2
后端需要提交的表单信息：
<pre>
{
  page1: {
    font: {
      color: "#fff"
    },
    background: {
      color: "#000"
    }
  }
  // page2...
}
</pre>

前端的表单设计：
<pre>
{
  page1: {
    properties: {
      font: {
        properties: {
          color: "配置"
        }
      },
      background: {
        properties: {
          color: "配置"
        }
      }
    }
  }
  // page2...
}
</pre>
这样可以一目了然地看出输入哪些字段。

数组确实可以确保所有的属性按顺序输出，而遍历Object时则会把纯数字的key先输出，其它的属性是按定义的顺序输出。

vue-easy-form目前对于纯数字作为属性名是有限制的，因为对于提交一个表单来说，纯数字作为属性名意义不大；因为要跟后端交互，即使用前端允许可这么写，后端也可能不允许；若真的需要纯数字作为属性名，后续可通过别名的方式解决这一短板。
