### ISSUE TITLE
如果我想使用 g-select 组件该如何使用呢？

### ISSUE THREAD

**Issue by zhaoeryu** [chengaohe45/vue-easy-form#2]

**Comment by chengaohe45** [comment]
g-select只不过是我写例子时，对el-select重新封装的一个组件，这样可让选择框更加容易配置，它并不属于vue-easy-form，所以你不能直接用g-select。
不过你可以重新封装一下el-select或利用插槽的方式直接配置el-select，插槽的方式可看看[组件插槽文档](https://chengaohe45.github.io/vue-easy-form-docs/dist/base/scopedSlots.html#%E9%85%8D%E7%BD%AE%E6%A0%BC%E5%BC%8F)，里面有说到el-select的配置方式

**Comment by zhaoeryu** [comment]
谢谢哈
