### ISSUE TITLE
强! awesome!

### ISSUE THREAD

**Issue by zhedream** [chengaohe45/vue-easy-form#4]
搜了一下 vue 动态表单, 第一个就是!
这么好的项目. 星星好少啊. 可能是平常使用的场景少吧
但是第一眼看文档和demo 调式页 就觉得超赞!
必须点个星 支持一下.
大佬有空可以实现下, react , angular 的
期待未来有更多的人用

**Comment by chengaohe45** [comment]
谢谢支持
