### ISSUE TITLE
如何实现表单联动效果？

### ISSUE THREAD

**Issue by DuanDuanPan** [chengaohe45/vue-easy-form#5]
譬如第一个field的值符合条件后，设置第二个field可编辑状态为否，这样的需求如何实现？

**Comment by chengaohe45** [comment]
esForm支持这样的联动的，可参考
[https://chengaohe45.github.io/vue-easy-form-docs/dist/base/parse.html](https://chengaohe45.github.io/vue-easy-form-docs/dist/base/parse.html)
（点击“开关切换“按钮或“当前global切换”按钮可看到效果）

像你上面所说，无非是控制某个属性，写法如下：
`
                field1: {
                  label: "姓名1",
                  component: "el-input",
                  value: ""
                },
             field2: {
                  label: "姓名2",
                  component: {
                    name: "el-input",
                    props: {
                      disabled: "es: !$root.field1"  // 当有值时可写
                    }
                  },
                  value: ""
                }
`

**Comment by chengaohe45** [comment]
esForm支持这样的联动的，可参考
[https://chengaohe45.github.io/vue-easy-form-docs/dist/base/parse.html](https://chengaohe45.github.io/vue-easy-form-docs/dist/base/parse.html)
（点击“开关切换“按钮或“当前global切换”按钮可看到效果）

像你上面所说，无非是控制某个属性，写法如下：
```
field1: {
    label: "姓名1",
    component: "el-input",
    value: ""
},

field2: {
    label: "姓名2",
    component: {
        name: "el-input",
        props: {
            disabled: "es: !$root.field1"  // 当有值时可写
        }
    },
    value: ""
}
```

**Comment by DuanDuanPan** [comment]
上面的json我这边是通过后台元数据服务动态构建的，所以props里面不会提前把所有element-ui的属性设置进去，我这边采用actions的方式
```javascript
name: {
                        label: '名称',
                        component: {
                            name: 'el-input',
                            props: {
                                placeholder: '请输入投放目标'
                            },
                            ref: 'nameRef', // 索引值，可以通过 form.getRef("testRef")取出
                            actions: [
                                {
                                    // 默认为click, 多个事件写法: ["change", "input"]或"change input"
                                    trigger: 'change',
                                    // options =>
                                    handler: ({value, event, pathKey, index, idxChain, target}) => {
                                        target.$parent.$parent.schema.component.props.disabled = true
                                    }
                                }
                            ], // 见下面
                            value: '首页位置' // 组件的默认值
                        }
                    }
```
存在的问题是第一次change事件触发没效果，失去焦点再进入文本框，输入新的字符才生效

**Comment by chengaohe45** [comment]
组件的属性值联动只能过props列举出来，并利用es语句或函数的写法进行控制（系统会自动传入解析数据源：如表单值$root）；

不能通过内部写法target.$parent.$parent.schema.component.props进行控制，因为target.$parent.$parent.schema会在初始化的时候生成一下标准的副本出来，这个副本会根据解析数据源变化重新计算出props里面的属性值。
