### ISSUE TITLE
可以支持 根据标准的json schema 语法 来动态生成表单吗？  

### ISSUE THREAD

**Issue by wang3690004** [chengaohe45/vue-easy-form#7]
请问一下 现有需求 是根据后端返回的一段json schema来动态生成一份表单，

 后端输出的就是标准的json schame语法，我看项目的formschame是那种自定义的语法结构 如果这样的话 会不会有局限性？

  请问 可以支持 根据标准的json schame语法 自动生成 基于 ant design1.x 的表单吗？

**Comment by chengaohe45** [comment]
直接使用标准的json schame是不可以的，自己要在中间做一份映射就可以了！
easy-form当初设计的目的就是不依赖于任何组件库，可以随意结合任务组件使用，包括使用element-ui/ant design或自定义的组件。easy-form的shema跟标准的json schema有所不同，如标准的json schema存在指定的类型type属性，easy-form摒弃这种设计，只结合组件使用，不认类型，因此easy-form并不知道组件是文本类型还是其它类型。若要实现标准的json schame语法输出一个 ant design1.x 的表单，自己要在中间做一份映射，json schame转化为easy-form schema!
