### ISSUE TITLE
showBody的打开和隐藏

### ISSUE THREAD

**Issue by daziweb** [chengaohe45/vue-easy-form#8]
建议再加一个参数控制showBoby的默认展开和隐藏，目前是默认展开的

**Comment by chengaohe45** [comment]
showBody有三个值false/true/不设置；
不设置代表没有切换按钮
false代表有切换按钮且默认收起
true代表有切换按钮且默认不收起，即打开
可参考：https://chengaohe45.github.io/vue-easy-form-docs/dist/base/properties.html
